BASE_URL = "https://operator.opus.com"
DEFAULT_TIMEOUT = 30.0
DEFAULT_MAX_RETRIES = 3
DEFAULT_POLL_INTERVAL = 2.0
DEFAULT_POLL_TIMEOUT = 300.0
SDK_VERSION = "0.1.0"
USER_AGENT = f"opus-aaico-python/{SDK_VERSION}"
